namespace Bot.Enums
{
    public enum ControllerStates
    {
        LoginToGrepolisPart1,
        LoginToGrepolisPart2,
        LoginToGrepolisPart3,
        LoggedIn,
        UpdateGameData,
        BuildingBuildData,
        UpdateTowns,
        UpdateUnits,
        SwitchTown,
        LocateFarmers,
        OpenFarmerWindow,
        GetTownSpecificData,
        LootFarmer,
        UnitsFarmer,
        CheckTrade,
        SendResources,
        UpdateCulturalInfo,
        StartCulturalFestival,
        CheckMainBuilding,
        CheckBuildingQueue,
        CheckBuildingQueueTeardown,
        FinishedCycle,
        OpenBarracksWindow,
        CheckLandUnitQueue,
        OpenDocksWindow,
        CheckNavyUnitQueue,
        CheckMilitia,
    }
}